name: Docker latest image

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
      - 'docs'
    branches: [main]
  workflow_dispatch:

env:
  GLOBAL_IMAGE_NAME: universalregistrar/uni-registrar-web
  GLOBAL_REPO_NAME: docker.io

jobs:

  build-context:
    runs-on: ubuntu-latest
    steps:
      - uses: danubetech/github-action-log-build-context@v0.1.0

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/${{ env.GLOBAL_REPO_NAME }} username | DOCKER_USERNAME ;
            ci/data/gh-workflows/${{ env.GLOBAL_REPO_NAME }} password | DOCKER_PASSWORD ;
            ci/data/gh-workflows/deployment-status slack-webhook-url | SLACK_WEBHOOK_URL

      - name: Build image
        run: docker build . -f uni-registrar-web/docker/Dockerfile -t "${{ env.GLOBAL_REPO_NAME }}/${{ env.GLOBAL_IMAGE_NAME }}"

      - name: Login user to repo
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login "${{ env.GLOBAL_REPO_NAME }}" -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Dockerhub
        run: docker push "${{ env.GLOBAL_REPO_NAME }}/${{ env.GLOBAL_IMAGE_NAME }}"

      - name: Slack notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}

  trigger-related-workflows:
    needs: [publish-image]
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/workflow-dispatch token | WORKFLOW_DISPATCH_TOKEN ;
            ci/data/gh-workflows/deployment-status slack-webhook-url | SLACK_WEBHOOK_URL

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: danubetech/danubetech-uni-registrar-web
          workflow: "Docker latest image" # Docker build

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: decentralized-identity/uni-registrar-driver-did-key
          workflow: 12949691 # Docker build

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: decentralized-identity/uni-registrar-driver-did-sov
          workflow: 6108957 # Docker build

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: decentralized-identity/uni-registrar-driver-did-btcr
          workflow: 6108951 # Docker build

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: decentralized-identity/uni-registrar-driver-did-v1
          workflow: 12885144 # Docker build

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: danubetech/uni-registrar-driver-did-ebsi
          workflow: 10383067 # Docker build

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: decentralized-identity/uni-registrar-driver-did-ion
          workflow: 6108961 # Docker build

      - name: Repository Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ env.WORKFLOW_DISPATCH_TOKEN }}
          repo: decentralized-identity/uni-registrar-driver-did-web
          workflow: 6108959 # Docker build

      - name: Slack notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
